spring:
  application:
    name: admin-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:leona}
    username: ${POSTGRES_USER:leona}
    password: ${POSTGRES_PASSWORD:leona}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 2s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER:https://auth.leonasec.io}

server:
  port: 8083
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      service: admin-service
      region: ${LEONA_REGION:local}

logging:
  level:
    root: INFO
    io.leonasec: DEBUG
