/*
 * Copyright 2026 Leona Contributors.
 * Licensed under the Apache License, Version 2.0.
 */
package io.leonasec.leona.config

import java.io.IOException

/**
 * Standardized attestation failure surfaced by Leona-compatible attestation bridges.
 */
class AttestationException(
    val provider: String,
    val code: String,
    val retryable: Boolean,
    message: String,
    cause: Throwable? = null,
) : IOException(message, cause)

object AttestationFailureCodes {
    const val ATTESTATION_PROVIDER_FAILED = "ATTESTATION_PROVIDER_FAILED"
    const val PLAY_INTEGRITY_NO_ERROR = "PLAY_INTEGRITY_NO_ERROR"
    const val PLAY_INTEGRITY_API_NOT_AVAILABLE = "PLAY_INTEGRITY_API_NOT_AVAILABLE"
    const val PLAY_INTEGRITY_PLAY_STORE_NOT_FOUND = "PLAY_INTEGRITY_PLAY_STORE_NOT_FOUND"
    const val PLAY_INTEGRITY_NETWORK_ERROR = "PLAY_INTEGRITY_NETWORK_ERROR"
    const val PLAY_INTEGRITY_APP_NOT_INSTALLED = "PLAY_INTEGRITY_APP_NOT_INSTALLED"
    const val PLAY_INTEGRITY_PLAY_SERVICES_NOT_FOUND = "PLAY_INTEGRITY_PLAY_SERVICES_NOT_FOUND"
    const val PLAY_INTEGRITY_APP_UID_MISMATCH = "PLAY_INTEGRITY_APP_UID_MISMATCH"
    const val PLAY_INTEGRITY_TOO_MANY_REQUESTS = "PLAY_INTEGRITY_TOO_MANY_REQUESTS"
    const val PLAY_INTEGRITY_CANNOT_BIND_TO_SERVICE = "PLAY_INTEGRITY_CANNOT_BIND_TO_SERVICE"
    const val PLAY_INTEGRITY_GOOGLE_SERVER_UNAVAILABLE = "PLAY_INTEGRITY_GOOGLE_SERVER_UNAVAILABLE"
    const val PLAY_INTEGRITY_PLAY_STORE_VERSION_OUTDATED = "PLAY_INTEGRITY_PLAY_STORE_VERSION_OUTDATED"
    const val PLAY_INTEGRITY_PLAY_SERVICES_VERSION_OUTDATED = "PLAY_INTEGRITY_PLAY_SERVICES_VERSION_OUTDATED"
    const val PLAY_INTEGRITY_CLOUD_PROJECT_NUMBER_IS_INVALID = "PLAY_INTEGRITY_CLOUD_PROJECT_NUMBER_IS_INVALID"
    const val PLAY_INTEGRITY_REQUEST_HASH_TOO_LONG = "PLAY_INTEGRITY_REQUEST_HASH_TOO_LONG"
    const val PLAY_INTEGRITY_CLIENT_TRANSIENT_ERROR = "PLAY_INTEGRITY_CLIENT_TRANSIENT_ERROR"
    const val PLAY_INTEGRITY_INTEGRITY_TOKEN_PROVIDER_INVALID = "PLAY_INTEGRITY_INTEGRITY_TOKEN_PROVIDER_INVALID"
    const val PLAY_INTEGRITY_INTERNAL_ERROR = "PLAY_INTEGRITY_INTERNAL_ERROR"
    const val PLAY_INTEGRITY_UNKNOWN = "PLAY_INTEGRITY_UNKNOWN"
}
