// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ingest.proto
// Protobuf Java Version: 4.29.4

package io.leonasec.proto.v1;

/**
 * Protobuf type {@code leona.evidence.v1.ClientScopeDeclaration}
 */
public  final class ClientScopeDeclaration extends
    com.google.protobuf.GeneratedMessageLite<
        ClientScopeDeclaration, ClientScopeDeclaration.Builder> implements
    // @@protoc_insertion_point(message_implements:leona.evidence.v1.ClientScopeDeclaration)
    ClientScopeDeclarationOrBuilder {
  private ClientScopeDeclaration() {
    tenantId_ = "";
    appId_ = "";
    environmentId_ = "";
  }
  public static final int TENANT_ID_FIELD_NUMBER = 1;
  private java.lang.String tenantId_;
  /**
   * <code>string tenant_id = 1;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    return tenantId_;
  }
  /**
   * <code>string tenant_id = 1;</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(tenantId_);
  }
  /**
   * <code>string tenant_id = 1;</code>
   * @param value The tenantId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTenantId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    tenantId_ = value;
  }
  /**
   * <code>string tenant_id = 1;</code>
   */
  private void clearTenantId() {

    tenantId_ = getDefaultInstance().getTenantId();
  }
  /**
   * <code>string tenant_id = 1;</code>
   * @param value The bytes for tenantId to set.
   */
  private void setTenantIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    tenantId_ = value.toStringUtf8();

  }

  public static final int APP_ID_FIELD_NUMBER = 2;
  private java.lang.String appId_;
  /**
   * <code>string app_id = 2;</code>
   * @return The appId.
   */
  @java.lang.Override
  public java.lang.String getAppId() {
    return appId_;
  }
  /**
   * <code>string app_id = 2;</code>
   * @return The bytes for appId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(appId_);
  }
  /**
   * <code>string app_id = 2;</code>
   * @param value The appId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setAppId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    appId_ = value;
  }
  /**
   * <code>string app_id = 2;</code>
   */
  private void clearAppId() {

    appId_ = getDefaultInstance().getAppId();
  }
  /**
   * <code>string app_id = 2;</code>
   * @param value The bytes for appId to set.
   */
  private void setAppIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    appId_ = value.toStringUtf8();

  }

  public static final int ENVIRONMENT_ID_FIELD_NUMBER = 3;
  private java.lang.String environmentId_;
  /**
   * <code>string environment_id = 3;</code>
   * @return The environmentId.
   */
  @java.lang.Override
  public java.lang.String getEnvironmentId() {
    return environmentId_;
  }
  /**
   * <code>string environment_id = 3;</code>
   * @return The bytes for environmentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEnvironmentIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(environmentId_);
  }
  /**
   * <code>string environment_id = 3;</code>
   * @param value The environmentId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setEnvironmentId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    environmentId_ = value;
  }
  /**
   * <code>string environment_id = 3;</code>
   */
  private void clearEnvironmentId() {

    environmentId_ = getDefaultInstance().getEnvironmentId();
  }
  /**
   * <code>string environment_id = 3;</code>
   * @param value The bytes for environmentId to set.
   */
  private void setEnvironmentIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    environmentId_ = value.toStringUtf8();

  }

  public static io.leonasec.proto.v1.ClientScopeDeclaration parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.leonasec.proto.v1.ClientScopeDeclaration parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.leonasec.proto.v1.ClientScopeDeclaration parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.leonasec.proto.v1.ClientScopeDeclaration parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.leonasec.proto.v1.ClientScopeDeclaration parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.leonasec.proto.v1.ClientScopeDeclaration parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.leonasec.proto.v1.ClientScopeDeclaration parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.leonasec.proto.v1.ClientScopeDeclaration parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.leonasec.proto.v1.ClientScopeDeclaration parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.leonasec.proto.v1.ClientScopeDeclaration parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.leonasec.proto.v1.ClientScopeDeclaration parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.leonasec.proto.v1.ClientScopeDeclaration parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.leonasec.proto.v1.ClientScopeDeclaration prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code leona.evidence.v1.ClientScopeDeclaration}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.leonasec.proto.v1.ClientScopeDeclaration, Builder> implements
      // @@protoc_insertion_point(builder_implements:leona.evidence.v1.ClientScopeDeclaration)
      io.leonasec.proto.v1.ClientScopeDeclarationOrBuilder {
    // Construct using io.leonasec.proto.v1.ClientScopeDeclaration.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string tenant_id = 1;</code>
     * @return The tenantId.
     */
    @java.lang.Override
    public java.lang.String getTenantId() {
      return instance.getTenantId();
    }
    /**
     * <code>string tenant_id = 1;</code>
     * @return The bytes for tenantId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      return instance.getTenantIdBytes();
    }
    /**
     * <code>string tenant_id = 1;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      copyOnWrite();
      instance.setTenantId(value);
      return this;
    }
    /**
     * <code>string tenant_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      copyOnWrite();
      instance.clearTenantId();
      return this;
    }
    /**
     * <code>string tenant_id = 1;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTenantIdBytes(value);
      return this;
    }

    /**
     * <code>string app_id = 2;</code>
     * @return The appId.
     */
    @java.lang.Override
    public java.lang.String getAppId() {
      return instance.getAppId();
    }
    /**
     * <code>string app_id = 2;</code>
     * @return The bytes for appId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      return instance.getAppIdBytes();
    }
    /**
     * <code>string app_id = 2;</code>
     * @param value The appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppId(
        java.lang.String value) {
      copyOnWrite();
      instance.setAppId(value);
      return this;
    }
    /**
     * <code>string app_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppId() {
      copyOnWrite();
      instance.clearAppId();
      return this;
    }
    /**
     * <code>string app_id = 2;</code>
     * @param value The bytes for appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAppIdBytes(value);
      return this;
    }

    /**
     * <code>string environment_id = 3;</code>
     * @return The environmentId.
     */
    @java.lang.Override
    public java.lang.String getEnvironmentId() {
      return instance.getEnvironmentId();
    }
    /**
     * <code>string environment_id = 3;</code>
     * @return The bytes for environmentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEnvironmentIdBytes() {
      return instance.getEnvironmentIdBytes();
    }
    /**
     * <code>string environment_id = 3;</code>
     * @param value The environmentId to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironmentId(
        java.lang.String value) {
      copyOnWrite();
      instance.setEnvironmentId(value);
      return this;
    }
    /**
     * <code>string environment_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnvironmentId() {
      copyOnWrite();
      instance.clearEnvironmentId();
      return this;
    }
    /**
     * <code>string environment_id = 3;</code>
     * @param value The bytes for environmentId to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironmentIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEnvironmentIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:leona.evidence.v1.ClientScopeDeclaration)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.leonasec.proto.v1.ClientScopeDeclaration();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "tenantId_",
            "appId_",
            "environmentId_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.leonasec.proto.v1.ClientScopeDeclaration> parser = PARSER;
        if (parser == null) {
          synchronized (io.leonasec.proto.v1.ClientScopeDeclaration.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.leonasec.proto.v1.ClientScopeDeclaration>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:leona.evidence.v1.ClientScopeDeclaration)
  private static final io.leonasec.proto.v1.ClientScopeDeclaration DEFAULT_INSTANCE;
  static {
    ClientScopeDeclaration defaultInstance = new ClientScopeDeclaration();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ClientScopeDeclaration.class, defaultInstance);
  }

  public static io.leonasec.proto.v1.ClientScopeDeclaration getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ClientScopeDeclaration> PARSER;

  public static com.google.protobuf.Parser<ClientScopeDeclaration> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

