// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ingest.proto
// Protobuf Java Version: 4.29.4

package io.leonasec.proto.v1;

public interface EvidenceBatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leona.evidence.v1.EvidenceBatch)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
   */
  java.util.List<io.leonasec.proto.v1.EvidenceEntry> 
      getEntriesList();
  /**
   * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
   */
  io.leonasec.proto.v1.EvidenceEntry getEntries(int index);
  /**
   * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
   */
  int getEntriesCount();
}
