// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ingest.proto
// Protobuf Java Version: 4.29.4

package io.leonasec.proto.v1;

/**
 * Protobuf type {@code leona.evidence.v1.EvidenceBatch}
 */
public  final class EvidenceBatch extends
    com.google.protobuf.GeneratedMessageLite<
        EvidenceBatch, EvidenceBatch.Builder> implements
    // @@protoc_insertion_point(message_implements:leona.evidence.v1.EvidenceBatch)
    EvidenceBatchOrBuilder {
  private EvidenceBatch() {
    entries_ = emptyProtobufList();
  }
  public static final int ENTRIES_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<io.leonasec.proto.v1.EvidenceEntry> entries_;
  /**
   * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.leonasec.proto.v1.EvidenceEntry> getEntriesList() {
    return entries_;
  }
  /**
   * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
   */
  public java.util.List<? extends io.leonasec.proto.v1.EvidenceEntryOrBuilder> 
      getEntriesOrBuilderList() {
    return entries_;
  }
  /**
   * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
   */
  @java.lang.Override
  public int getEntriesCount() {
    return entries_.size();
  }
  /**
   * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
   */
  @java.lang.Override
  public io.leonasec.proto.v1.EvidenceEntry getEntries(int index) {
    return entries_.get(index);
  }
  /**
   * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
   */
  public io.leonasec.proto.v1.EvidenceEntryOrBuilder getEntriesOrBuilder(
      int index) {
    return entries_.get(index);
  }
  private void ensureEntriesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<io.leonasec.proto.v1.EvidenceEntry> tmp = entries_;
    if (!tmp.isModifiable()) {
      entries_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setEntries(
      int index, io.leonasec.proto.v1.EvidenceEntry value) {
    value.getClass();  // minimal bytecode null check
    ensureEntriesIsMutable();
    entries_.set(index, value);
  }
  /**
   * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addEntries(io.leonasec.proto.v1.EvidenceEntry value) {
    value.getClass();  // minimal bytecode null check
    ensureEntriesIsMutable();
    entries_.add(value);
  }
  /**
   * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addEntries(
      int index, io.leonasec.proto.v1.EvidenceEntry value) {
    value.getClass();  // minimal bytecode null check
    ensureEntriesIsMutable();
    entries_.add(index, value);
  }
  /**
   * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
   */
  private void addAllEntries(
      java.lang.Iterable<? extends io.leonasec.proto.v1.EvidenceEntry> values) {
    ensureEntriesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, entries_);
  }
  /**
   * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
   */
  private void clearEntries() {
    entries_ = emptyProtobufList();
  }
  /**
   * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
   */
  private void removeEntries(int index) {
    ensureEntriesIsMutable();
    entries_.remove(index);
  }

  public static io.leonasec.proto.v1.EvidenceBatch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.leonasec.proto.v1.EvidenceBatch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.leonasec.proto.v1.EvidenceBatch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.leonasec.proto.v1.EvidenceBatch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.leonasec.proto.v1.EvidenceBatch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.leonasec.proto.v1.EvidenceBatch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.leonasec.proto.v1.EvidenceBatch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.leonasec.proto.v1.EvidenceBatch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.leonasec.proto.v1.EvidenceBatch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.leonasec.proto.v1.EvidenceBatch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.leonasec.proto.v1.EvidenceBatch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.leonasec.proto.v1.EvidenceBatch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.leonasec.proto.v1.EvidenceBatch prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code leona.evidence.v1.EvidenceBatch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.leonasec.proto.v1.EvidenceBatch, Builder> implements
      // @@protoc_insertion_point(builder_implements:leona.evidence.v1.EvidenceBatch)
      io.leonasec.proto.v1.EvidenceBatchOrBuilder {
    // Construct using io.leonasec.proto.v1.EvidenceBatch.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
     */
    @java.lang.Override
    public java.util.List<io.leonasec.proto.v1.EvidenceEntry> getEntriesList() {
      return java.util.Collections.unmodifiableList(
          instance.getEntriesList());
    }
    /**
     * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
     */
    @java.lang.Override
    public int getEntriesCount() {
      return instance.getEntriesCount();
    }/**
     * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
     */
    @java.lang.Override
    public io.leonasec.proto.v1.EvidenceEntry getEntries(int index) {
      return instance.getEntries(index);
    }
    /**
     * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
     */
    public Builder setEntries(
        int index, io.leonasec.proto.v1.EvidenceEntry value) {
      copyOnWrite();
      instance.setEntries(index, value);
      return this;
    }
    /**
     * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
     */
    public Builder setEntries(
        int index, io.leonasec.proto.v1.EvidenceEntry.Builder builderForValue) {
      copyOnWrite();
      instance.setEntries(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
     */
    public Builder addEntries(io.leonasec.proto.v1.EvidenceEntry value) {
      copyOnWrite();
      instance.addEntries(value);
      return this;
    }
    /**
     * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
     */
    public Builder addEntries(
        int index, io.leonasec.proto.v1.EvidenceEntry value) {
      copyOnWrite();
      instance.addEntries(index, value);
      return this;
    }
    /**
     * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
     */
    public Builder addEntries(
        io.leonasec.proto.v1.EvidenceEntry.Builder builderForValue) {
      copyOnWrite();
      instance.addEntries(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
     */
    public Builder addEntries(
        int index, io.leonasec.proto.v1.EvidenceEntry.Builder builderForValue) {
      copyOnWrite();
      instance.addEntries(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
     */
    public Builder addAllEntries(
        java.lang.Iterable<? extends io.leonasec.proto.v1.EvidenceEntry> values) {
      copyOnWrite();
      instance.addAllEntries(values);
      return this;
    }
    /**
     * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
     */
    public Builder clearEntries() {
      copyOnWrite();
      instance.clearEntries();
      return this;
    }
    /**
     * <code>repeated .leona.evidence.v1.EvidenceEntry entries = 1;</code>
     */
    public Builder removeEntries(int index) {
      copyOnWrite();
      instance.removeEntries(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:leona.evidence.v1.EvidenceBatch)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.leonasec.proto.v1.EvidenceBatch();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "entries_",
            io.leonasec.proto.v1.EvidenceEntry.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.leonasec.proto.v1.EvidenceBatch> parser = PARSER;
        if (parser == null) {
          synchronized (io.leonasec.proto.v1.EvidenceBatch.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.leonasec.proto.v1.EvidenceBatch>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:leona.evidence.v1.EvidenceBatch)
  private static final io.leonasec.proto.v1.EvidenceBatch DEFAULT_INSTANCE;
  static {
    EvidenceBatch defaultInstance = new EvidenceBatch();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      EvidenceBatch.class, defaultInstance);
  }

  public static io.leonasec.proto.v1.EvidenceBatch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<EvidenceBatch> PARSER;

  public static com.google.protobuf.Parser<EvidenceBatch> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

