// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ingest.proto
// Protobuf Java Version: 4.29.4

package io.leonasec.proto.v1;

/**
 * Protobuf enum {@code leona.evidence.v1.EvidenceEnum}
 */
public enum EvidenceEnum
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>EVIDENCE_ENUM_UNSPECIFIED = 0;</code>
   */
  EVIDENCE_ENUM_UNSPECIFIED(0),
  /**
   * <code>EVIDENCE_ENUM_TRUE = 1;</code>
   */
  EVIDENCE_ENUM_TRUE(1),
  /**
   * <code>EVIDENCE_ENUM_FALSE = 2;</code>
   */
  EVIDENCE_ENUM_FALSE(2),
  /**
   * <code>EVIDENCE_ENUM_UNKNOWN = 3;</code>
   */
  EVIDENCE_ENUM_UNKNOWN(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>EVIDENCE_ENUM_UNSPECIFIED = 0;</code>
   */
  public static final int EVIDENCE_ENUM_UNSPECIFIED_VALUE = 0;
  /**
   * <code>EVIDENCE_ENUM_TRUE = 1;</code>
   */
  public static final int EVIDENCE_ENUM_TRUE_VALUE = 1;
  /**
   * <code>EVIDENCE_ENUM_FALSE = 2;</code>
   */
  public static final int EVIDENCE_ENUM_FALSE_VALUE = 2;
  /**
   * <code>EVIDENCE_ENUM_UNKNOWN = 3;</code>
   */
  public static final int EVIDENCE_ENUM_UNKNOWN_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EvidenceEnum valueOf(int value) {
    return forNumber(value);
  }

  public static EvidenceEnum forNumber(int value) {
    switch (value) {
      case 0: return EVIDENCE_ENUM_UNSPECIFIED;
      case 1: return EVIDENCE_ENUM_TRUE;
      case 2: return EVIDENCE_ENUM_FALSE;
      case 3: return EVIDENCE_ENUM_UNKNOWN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EvidenceEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EvidenceEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EvidenceEnum>() {
          @java.lang.Override
          public EvidenceEnum findValueByNumber(int number) {
            return EvidenceEnum.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return EvidenceEnumVerifier.INSTANCE;
  }

  private static final class EvidenceEnumVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new EvidenceEnumVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return EvidenceEnum.forNumber(number) != null;
          }
        };

  private final int value;

  private EvidenceEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:leona.evidence.v1.EvidenceEnum)
}

