// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ingest.proto
// Protobuf Java Version: 4.29.4

package io.leonasec.proto.v1;

/**
 * Protobuf enum {@code leona.evidence.v1.EvidenceSource}
 */
public enum EvidenceSource
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>EVIDENCE_SOURCE_UNSPECIFIED = 0;</code>
   */
  EVIDENCE_SOURCE_UNSPECIFIED(0),
  /**
   * <code>EVIDENCE_SOURCE_ANDROID = 1;</code>
   */
  EVIDENCE_SOURCE_ANDROID(1),
  /**
   * <code>EVIDENCE_SOURCE_LEO_PROVIDER = 2;</code>
   */
  EVIDENCE_SOURCE_LEO_PROVIDER(2),
  /**
   * <code>EVIDENCE_SOURCE_PLATFORM = 3;</code>
   */
  EVIDENCE_SOURCE_PLATFORM(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>EVIDENCE_SOURCE_UNSPECIFIED = 0;</code>
   */
  public static final int EVIDENCE_SOURCE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>EVIDENCE_SOURCE_ANDROID = 1;</code>
   */
  public static final int EVIDENCE_SOURCE_ANDROID_VALUE = 1;
  /**
   * <code>EVIDENCE_SOURCE_LEO_PROVIDER = 2;</code>
   */
  public static final int EVIDENCE_SOURCE_LEO_PROVIDER_VALUE = 2;
  /**
   * <code>EVIDENCE_SOURCE_PLATFORM = 3;</code>
   */
  public static final int EVIDENCE_SOURCE_PLATFORM_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EvidenceSource valueOf(int value) {
    return forNumber(value);
  }

  public static EvidenceSource forNumber(int value) {
    switch (value) {
      case 0: return EVIDENCE_SOURCE_UNSPECIFIED;
      case 1: return EVIDENCE_SOURCE_ANDROID;
      case 2: return EVIDENCE_SOURCE_LEO_PROVIDER;
      case 3: return EVIDENCE_SOURCE_PLATFORM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EvidenceSource>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EvidenceSource> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EvidenceSource>() {
          @java.lang.Override
          public EvidenceSource findValueByNumber(int number) {
            return EvidenceSource.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return EvidenceSourceVerifier.INSTANCE;
  }

  private static final class EvidenceSourceVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new EvidenceSourceVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return EvidenceSource.forNumber(number) != null;
          }
        };

  private final int value;

  private EvidenceSource(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:leona.evidence.v1.EvidenceSource)
}

