// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ingest.proto
// Protobuf Java Version: 4.29.4

package io.leonasec.proto.v1;

public interface EvidenceIngestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leona.evidence.v1.EvidenceIngestRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 protocol_major = 1;</code>
   * @return The protocolMajor.
   */
  int getProtocolMajor();

  /**
   * <code>string tenant_id = 2;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 2;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string app_id = 3;</code>
   * @return The appId.
   */
  java.lang.String getAppId();
  /**
   * <code>string app_id = 3;</code>
   * @return The bytes for appId.
   */
  com.google.protobuf.ByteString
      getAppIdBytes();

  /**
   * <code>string environment_id = 4;</code>
   * @return The environmentId.
   */
  java.lang.String getEnvironmentId();
  /**
   * <code>string environment_id = 4;</code>
   * @return The bytes for environmentId.
   */
  com.google.protobuf.ByteString
      getEnvironmentIdBytes();

  /**
   * <code>string install_id = 5;</code>
   * @return The installId.
   */
  java.lang.String getInstallId();
  /**
   * <code>string install_id = 5;</code>
   * @return The bytes for installId.
   */
  com.google.protobuf.ByteString
      getInstallIdBytes();

  /**
   * <code>string session_id = 6;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 6;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string request_id = 7;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 7;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>bytes nonce = 8;</code>
   * @return The nonce.
   */
  com.google.protobuf.ByteString getNonce();

  /**
   * <code>string idempotency_key = 9;</code>
   * @return The idempotencyKey.
   */
  java.lang.String getIdempotencyKey();
  /**
   * <code>string idempotency_key = 9;</code>
   * @return The bytes for idempotencyKey.
   */
  com.google.protobuf.ByteString
      getIdempotencyKeyBytes();

  /**
   * <code>int64 issued_at_epoch_ms = 10;</code>
   * @return The issuedAtEpochMs.
   */
  long getIssuedAtEpochMs();

  /**
   * <code>.leona.evidence.v1.ClientScopeDeclaration client_scope = 11;</code>
   * @return Whether the clientScope field is set.
   */
  boolean hasClientScope();
  /**
   * <code>.leona.evidence.v1.ClientScopeDeclaration client_scope = 11;</code>
   * @return The clientScope.
   */
  io.leonasec.proto.v1.ClientScopeDeclaration getClientScope();

  /**
   * <code>.leona.evidence.v1.EvidenceBatch evidence_batch = 12;</code>
   * @return Whether the evidenceBatch field is set.
   */
  boolean hasEvidenceBatch();
  /**
   * <code>.leona.evidence.v1.EvidenceBatch evidence_batch = 12;</code>
   * @return The evidenceBatch.
   */
  io.leonasec.proto.v1.EvidenceBatch getEvidenceBatch();
}
