// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ingest.proto
// Protobuf Java Version: 4.29.4

package io.leonasec.proto.v1;

public interface EvidenceEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leona.evidence.v1.EvidenceEntry)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>int64 observed_at_epoch_ms = 2;</code>
   * @return The observedAtEpochMs.
   */
  long getObservedAtEpochMs();

  /**
   * <code>.leona.evidence.v1.EvidenceSource source = 3;</code>
   * @return The enum numeric value on the wire for source.
   */
  int getSourceValue();
  /**
   * <code>.leona.evidence.v1.EvidenceSource source = 3;</code>
   * @return The source.
   */
  io.leonasec.proto.v1.EvidenceSource getSource();

  /**
   * <code>.leona.evidence.v1.EvidenceQuality quality = 4;</code>
   * @return The enum numeric value on the wire for quality.
   */
  int getQualityValue();
  /**
   * <code>.leona.evidence.v1.EvidenceQuality quality = 4;</code>
   * @return The quality.
   */
  io.leonasec.proto.v1.EvidenceQuality getQuality();

  /**
   * <code>bool bool_value = 5;</code>
   * @return Whether the boolValue field is set.
   */
  boolean hasBoolValue();
  /**
   * <code>bool bool_value = 5;</code>
   * @return The boolValue.
   */
  boolean getBoolValue();

  /**
   * <code>sint64 int_value = 6;</code>
   * @return Whether the intValue field is set.
   */
  boolean hasIntValue();
  /**
   * <code>sint64 int_value = 6;</code>
   * @return The intValue.
   */
  long getIntValue();

  /**
   * <code>fixed64 uint_value = 7;</code>
   * @return Whether the uintValue field is set.
   */
  boolean hasUintValue();
  /**
   * <code>fixed64 uint_value = 7;</code>
   * @return The uintValue.
   */
  long getUintValue();

  /**
   * <code>string string_value = 8;</code>
   * @return Whether the stringValue field is set.
   */
  boolean hasStringValue();
  /**
   * <code>string string_value = 8;</code>
   * @return The stringValue.
   */
  java.lang.String getStringValue();
  /**
   * <code>string string_value = 8;</code>
   * @return The bytes for stringValue.
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>bytes bytes_value = 9;</code>
   * @return Whether the bytesValue field is set.
   */
  boolean hasBytesValue();
  /**
   * <code>bytes bytes_value = 9;</code>
   * @return The bytesValue.
   */
  com.google.protobuf.ByteString getBytesValue();

  /**
   * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
   * @return Whether the enumValue field is set.
   */
  boolean hasEnumValue();
  /**
   * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
   * @return The enum numeric value on the wire for enumValue.
   */
  int getEnumValueValue();
  /**
   * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
   * @return The enumValue.
   */
  io.leonasec.proto.v1.EvidenceEnum getEnumValue();

  public io.leonasec.proto.v1.EvidenceEntry.ValueCase getValueCase();
}
