// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ingest.proto
// Protobuf Java Version: 4.29.4

package io.leonasec.proto.v1;

/**
 * <pre>
 * Provider-verified, evidence-only ingress.  Scope, identity and verdict
 * authority remain server-side; client declarations are comparison inputs.
 * </pre>
 *
 * Protobuf type {@code leona.evidence.v1.EvidenceIngestRequest}
 */
public  final class EvidenceIngestRequest extends
    com.google.protobuf.GeneratedMessageLite<
        EvidenceIngestRequest, EvidenceIngestRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:leona.evidence.v1.EvidenceIngestRequest)
    EvidenceIngestRequestOrBuilder {
  private EvidenceIngestRequest() {
    tenantId_ = "";
    appId_ = "";
    environmentId_ = "";
    installId_ = "";
    sessionId_ = "";
    requestId_ = "";
    nonce_ = com.google.protobuf.ByteString.EMPTY;
    idempotencyKey_ = "";
  }
  private int bitField0_;
  public static final int PROTOCOL_MAJOR_FIELD_NUMBER = 1;
  private int protocolMajor_;
  /**
   * <code>uint32 protocol_major = 1;</code>
   * @return The protocolMajor.
   */
  @java.lang.Override
  public int getProtocolMajor() {
    return protocolMajor_;
  }
  /**
   * <code>uint32 protocol_major = 1;</code>
   * @param value The protocolMajor to set.
   */
  private void setProtocolMajor(int value) {
    
    protocolMajor_ = value;
  }
  /**
   * <code>uint32 protocol_major = 1;</code>
   */
  private void clearProtocolMajor() {

    protocolMajor_ = 0;
  }

  public static final int TENANT_ID_FIELD_NUMBER = 2;
  private java.lang.String tenantId_;
  /**
   * <code>string tenant_id = 2;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    return tenantId_;
  }
  /**
   * <code>string tenant_id = 2;</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(tenantId_);
  }
  /**
   * <code>string tenant_id = 2;</code>
   * @param value The tenantId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTenantId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    tenantId_ = value;
  }
  /**
   * <code>string tenant_id = 2;</code>
   */
  private void clearTenantId() {

    tenantId_ = getDefaultInstance().getTenantId();
  }
  /**
   * <code>string tenant_id = 2;</code>
   * @param value The bytes for tenantId to set.
   */
  private void setTenantIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    tenantId_ = value.toStringUtf8();

  }

  public static final int APP_ID_FIELD_NUMBER = 3;
  private java.lang.String appId_;
  /**
   * <code>string app_id = 3;</code>
   * @return The appId.
   */
  @java.lang.Override
  public java.lang.String getAppId() {
    return appId_;
  }
  /**
   * <code>string app_id = 3;</code>
   * @return The bytes for appId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(appId_);
  }
  /**
   * <code>string app_id = 3;</code>
   * @param value The appId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setAppId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    appId_ = value;
  }
  /**
   * <code>string app_id = 3;</code>
   */
  private void clearAppId() {

    appId_ = getDefaultInstance().getAppId();
  }
  /**
   * <code>string app_id = 3;</code>
   * @param value The bytes for appId to set.
   */
  private void setAppIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    appId_ = value.toStringUtf8();

  }

  public static final int ENVIRONMENT_ID_FIELD_NUMBER = 4;
  private java.lang.String environmentId_;
  /**
   * <code>string environment_id = 4;</code>
   * @return The environmentId.
   */
  @java.lang.Override
  public java.lang.String getEnvironmentId() {
    return environmentId_;
  }
  /**
   * <code>string environment_id = 4;</code>
   * @return The bytes for environmentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEnvironmentIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(environmentId_);
  }
  /**
   * <code>string environment_id = 4;</code>
   * @param value The environmentId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setEnvironmentId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    environmentId_ = value;
  }
  /**
   * <code>string environment_id = 4;</code>
   */
  private void clearEnvironmentId() {

    environmentId_ = getDefaultInstance().getEnvironmentId();
  }
  /**
   * <code>string environment_id = 4;</code>
   * @param value The bytes for environmentId to set.
   */
  private void setEnvironmentIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    environmentId_ = value.toStringUtf8();

  }

  public static final int INSTALL_ID_FIELD_NUMBER = 5;
  private java.lang.String installId_;
  /**
   * <code>string install_id = 5;</code>
   * @return The installId.
   */
  @java.lang.Override
  public java.lang.String getInstallId() {
    return installId_;
  }
  /**
   * <code>string install_id = 5;</code>
   * @return The bytes for installId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInstallIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(installId_);
  }
  /**
   * <code>string install_id = 5;</code>
   * @param value The installId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setInstallId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    installId_ = value;
  }
  /**
   * <code>string install_id = 5;</code>
   */
  private void clearInstallId() {

    installId_ = getDefaultInstance().getInstallId();
  }
  /**
   * <code>string install_id = 5;</code>
   * @param value The bytes for installId to set.
   */
  private void setInstallIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    installId_ = value.toStringUtf8();

  }

  public static final int SESSION_ID_FIELD_NUMBER = 6;
  private java.lang.String sessionId_;
  /**
   * <code>string session_id = 6;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    return sessionId_;
  }
  /**
   * <code>string session_id = 6;</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sessionId_);
  }
  /**
   * <code>string session_id = 6;</code>
   * @param value The sessionId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSessionId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    sessionId_ = value;
  }
  /**
   * <code>string session_id = 6;</code>
   */
  private void clearSessionId() {

    sessionId_ = getDefaultInstance().getSessionId();
  }
  /**
   * <code>string session_id = 6;</code>
   * @param value The bytes for sessionId to set.
   */
  private void setSessionIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    sessionId_ = value.toStringUtf8();

  }

  public static final int REQUEST_ID_FIELD_NUMBER = 7;
  private java.lang.String requestId_;
  /**
   * <code>string request_id = 7;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public java.lang.String getRequestId() {
    return requestId_;
  }
  /**
   * <code>string request_id = 7;</code>
   * @return The bytes for requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(requestId_);
  }
  /**
   * <code>string request_id = 7;</code>
   * @param value The requestId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRequestId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    requestId_ = value;
  }
  /**
   * <code>string request_id = 7;</code>
   */
  private void clearRequestId() {

    requestId_ = getDefaultInstance().getRequestId();
  }
  /**
   * <code>string request_id = 7;</code>
   * @param value The bytes for requestId to set.
   */
  private void setRequestIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    requestId_ = value.toStringUtf8();

  }

  public static final int NONCE_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString nonce_;
  /**
   * <code>bytes nonce = 8;</code>
   * @return The nonce.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNonce() {
    return nonce_;
  }
  /**
   * <code>bytes nonce = 8;</code>
   * @param value The nonce to set.
   */
  private void setNonce(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    nonce_ = value;
  }
  /**
   * <code>bytes nonce = 8;</code>
   */
  private void clearNonce() {

    nonce_ = getDefaultInstance().getNonce();
  }

  public static final int IDEMPOTENCY_KEY_FIELD_NUMBER = 9;
  private java.lang.String idempotencyKey_;
  /**
   * <code>string idempotency_key = 9;</code>
   * @return The idempotencyKey.
   */
  @java.lang.Override
  public java.lang.String getIdempotencyKey() {
    return idempotencyKey_;
  }
  /**
   * <code>string idempotency_key = 9;</code>
   * @return The bytes for idempotencyKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdempotencyKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(idempotencyKey_);
  }
  /**
   * <code>string idempotency_key = 9;</code>
   * @param value The idempotencyKey to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setIdempotencyKey(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    idempotencyKey_ = value;
  }
  /**
   * <code>string idempotency_key = 9;</code>
   */
  private void clearIdempotencyKey() {

    idempotencyKey_ = getDefaultInstance().getIdempotencyKey();
  }
  /**
   * <code>string idempotency_key = 9;</code>
   * @param value The bytes for idempotencyKey to set.
   */
  private void setIdempotencyKeyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    idempotencyKey_ = value.toStringUtf8();

  }

  public static final int ISSUED_AT_EPOCH_MS_FIELD_NUMBER = 10;
  private long issuedAtEpochMs_;
  /**
   * <code>int64 issued_at_epoch_ms = 10;</code>
   * @return The issuedAtEpochMs.
   */
  @java.lang.Override
  public long getIssuedAtEpochMs() {
    return issuedAtEpochMs_;
  }
  /**
   * <code>int64 issued_at_epoch_ms = 10;</code>
   * @param value The issuedAtEpochMs to set.
   */
  private void setIssuedAtEpochMs(long value) {
    
    issuedAtEpochMs_ = value;
  }
  /**
   * <code>int64 issued_at_epoch_ms = 10;</code>
   */
  private void clearIssuedAtEpochMs() {

    issuedAtEpochMs_ = 0L;
  }

  public static final int CLIENT_SCOPE_FIELD_NUMBER = 11;
  private io.leonasec.proto.v1.ClientScopeDeclaration clientScope_;
  /**
   * <code>.leona.evidence.v1.ClientScopeDeclaration client_scope = 11;</code>
   */
  @java.lang.Override
  public boolean hasClientScope() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.leona.evidence.v1.ClientScopeDeclaration client_scope = 11;</code>
   */
  @java.lang.Override
  public io.leonasec.proto.v1.ClientScopeDeclaration getClientScope() {
    return clientScope_ == null ? io.leonasec.proto.v1.ClientScopeDeclaration.getDefaultInstance() : clientScope_;
  }
  /**
   * <code>.leona.evidence.v1.ClientScopeDeclaration client_scope = 11;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setClientScope(io.leonasec.proto.v1.ClientScopeDeclaration value) {
    value.getClass();  // minimal bytecode null check
    clientScope_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.leona.evidence.v1.ClientScopeDeclaration client_scope = 11;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeClientScope(io.leonasec.proto.v1.ClientScopeDeclaration value) {
    value.getClass();  // minimal bytecode null check
    if (clientScope_ != null &&
        clientScope_ != io.leonasec.proto.v1.ClientScopeDeclaration.getDefaultInstance()) {
      clientScope_ =
        io.leonasec.proto.v1.ClientScopeDeclaration.newBuilder(clientScope_).mergeFrom(value).buildPartial();
    } else {
      clientScope_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.leona.evidence.v1.ClientScopeDeclaration client_scope = 11;</code>
   */
  private void clearClientScope() {  clientScope_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int EVIDENCE_BATCH_FIELD_NUMBER = 12;
  private io.leonasec.proto.v1.EvidenceBatch evidenceBatch_;
  /**
   * <code>.leona.evidence.v1.EvidenceBatch evidence_batch = 12;</code>
   */
  @java.lang.Override
  public boolean hasEvidenceBatch() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.leona.evidence.v1.EvidenceBatch evidence_batch = 12;</code>
   */
  @java.lang.Override
  public io.leonasec.proto.v1.EvidenceBatch getEvidenceBatch() {
    return evidenceBatch_ == null ? io.leonasec.proto.v1.EvidenceBatch.getDefaultInstance() : evidenceBatch_;
  }
  /**
   * <code>.leona.evidence.v1.EvidenceBatch evidence_batch = 12;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setEvidenceBatch(io.leonasec.proto.v1.EvidenceBatch value) {
    value.getClass();  // minimal bytecode null check
    evidenceBatch_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <code>.leona.evidence.v1.EvidenceBatch evidence_batch = 12;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeEvidenceBatch(io.leonasec.proto.v1.EvidenceBatch value) {
    value.getClass();  // minimal bytecode null check
    if (evidenceBatch_ != null &&
        evidenceBatch_ != io.leonasec.proto.v1.EvidenceBatch.getDefaultInstance()) {
      evidenceBatch_ =
        io.leonasec.proto.v1.EvidenceBatch.newBuilder(evidenceBatch_).mergeFrom(value).buildPartial();
    } else {
      evidenceBatch_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>.leona.evidence.v1.EvidenceBatch evidence_batch = 12;</code>
   */
  private void clearEvidenceBatch() {  evidenceBatch_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static io.leonasec.proto.v1.EvidenceIngestRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.leonasec.proto.v1.EvidenceIngestRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.leonasec.proto.v1.EvidenceIngestRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.leonasec.proto.v1.EvidenceIngestRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.leonasec.proto.v1.EvidenceIngestRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.leonasec.proto.v1.EvidenceIngestRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.leonasec.proto.v1.EvidenceIngestRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.leonasec.proto.v1.EvidenceIngestRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.leonasec.proto.v1.EvidenceIngestRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.leonasec.proto.v1.EvidenceIngestRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.leonasec.proto.v1.EvidenceIngestRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.leonasec.proto.v1.EvidenceIngestRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.leonasec.proto.v1.EvidenceIngestRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Provider-verified, evidence-only ingress.  Scope, identity and verdict
   * authority remain server-side; client declarations are comparison inputs.
   * </pre>
   *
   * Protobuf type {@code leona.evidence.v1.EvidenceIngestRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.leonasec.proto.v1.EvidenceIngestRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:leona.evidence.v1.EvidenceIngestRequest)
      io.leonasec.proto.v1.EvidenceIngestRequestOrBuilder {
    // Construct using io.leonasec.proto.v1.EvidenceIngestRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint32 protocol_major = 1;</code>
     * @return The protocolMajor.
     */
    @java.lang.Override
    public int getProtocolMajor() {
      return instance.getProtocolMajor();
    }
    /**
     * <code>uint32 protocol_major = 1;</code>
     * @param value The protocolMajor to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolMajor(int value) {
      copyOnWrite();
      instance.setProtocolMajor(value);
      return this;
    }
    /**
     * <code>uint32 protocol_major = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocolMajor() {
      copyOnWrite();
      instance.clearProtocolMajor();
      return this;
    }

    /**
     * <code>string tenant_id = 2;</code>
     * @return The tenantId.
     */
    @java.lang.Override
    public java.lang.String getTenantId() {
      return instance.getTenantId();
    }
    /**
     * <code>string tenant_id = 2;</code>
     * @return The bytes for tenantId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      return instance.getTenantIdBytes();
    }
    /**
     * <code>string tenant_id = 2;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      copyOnWrite();
      instance.setTenantId(value);
      return this;
    }
    /**
     * <code>string tenant_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      copyOnWrite();
      instance.clearTenantId();
      return this;
    }
    /**
     * <code>string tenant_id = 2;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTenantIdBytes(value);
      return this;
    }

    /**
     * <code>string app_id = 3;</code>
     * @return The appId.
     */
    @java.lang.Override
    public java.lang.String getAppId() {
      return instance.getAppId();
    }
    /**
     * <code>string app_id = 3;</code>
     * @return The bytes for appId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      return instance.getAppIdBytes();
    }
    /**
     * <code>string app_id = 3;</code>
     * @param value The appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppId(
        java.lang.String value) {
      copyOnWrite();
      instance.setAppId(value);
      return this;
    }
    /**
     * <code>string app_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppId() {
      copyOnWrite();
      instance.clearAppId();
      return this;
    }
    /**
     * <code>string app_id = 3;</code>
     * @param value The bytes for appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAppIdBytes(value);
      return this;
    }

    /**
     * <code>string environment_id = 4;</code>
     * @return The environmentId.
     */
    @java.lang.Override
    public java.lang.String getEnvironmentId() {
      return instance.getEnvironmentId();
    }
    /**
     * <code>string environment_id = 4;</code>
     * @return The bytes for environmentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEnvironmentIdBytes() {
      return instance.getEnvironmentIdBytes();
    }
    /**
     * <code>string environment_id = 4;</code>
     * @param value The environmentId to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironmentId(
        java.lang.String value) {
      copyOnWrite();
      instance.setEnvironmentId(value);
      return this;
    }
    /**
     * <code>string environment_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnvironmentId() {
      copyOnWrite();
      instance.clearEnvironmentId();
      return this;
    }
    /**
     * <code>string environment_id = 4;</code>
     * @param value The bytes for environmentId to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironmentIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEnvironmentIdBytes(value);
      return this;
    }

    /**
     * <code>string install_id = 5;</code>
     * @return The installId.
     */
    @java.lang.Override
    public java.lang.String getInstallId() {
      return instance.getInstallId();
    }
    /**
     * <code>string install_id = 5;</code>
     * @return The bytes for installId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInstallIdBytes() {
      return instance.getInstallIdBytes();
    }
    /**
     * <code>string install_id = 5;</code>
     * @param value The installId to set.
     * @return This builder for chaining.
     */
    public Builder setInstallId(
        java.lang.String value) {
      copyOnWrite();
      instance.setInstallId(value);
      return this;
    }
    /**
     * <code>string install_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearInstallId() {
      copyOnWrite();
      instance.clearInstallId();
      return this;
    }
    /**
     * <code>string install_id = 5;</code>
     * @param value The bytes for installId to set.
     * @return This builder for chaining.
     */
    public Builder setInstallIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setInstallIdBytes(value);
      return this;
    }

    /**
     * <code>string session_id = 6;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public java.lang.String getSessionId() {
      return instance.getSessionId();
    }
    /**
     * <code>string session_id = 6;</code>
     * @return The bytes for sessionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      return instance.getSessionIdBytes();
    }
    /**
     * <code>string session_id = 6;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSessionId(value);
      return this;
    }
    /**
     * <code>string session_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      copyOnWrite();
      instance.clearSessionId();
      return this;
    }
    /**
     * <code>string session_id = 6;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSessionIdBytes(value);
      return this;
    }

    /**
     * <code>string request_id = 7;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public java.lang.String getRequestId() {
      return instance.getRequestId();
    }
    /**
     * <code>string request_id = 7;</code>
     * @return The bytes for requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      return instance.getRequestIdBytes();
    }
    /**
     * <code>string request_id = 7;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRequestId(value);
      return this;
    }
    /**
     * <code>string request_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      copyOnWrite();
      instance.clearRequestId();
      return this;
    }
    /**
     * <code>string request_id = 7;</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRequestIdBytes(value);
      return this;
    }

    /**
     * <code>bytes nonce = 8;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNonce() {
      return instance.getNonce();
    }
    /**
     * <code>bytes nonce = 8;</code>
     * @param value The nonce to set.
     * @return This builder for chaining.
     */
    public Builder setNonce(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNonce(value);
      return this;
    }
    /**
     * <code>bytes nonce = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonce() {
      copyOnWrite();
      instance.clearNonce();
      return this;
    }

    /**
     * <code>string idempotency_key = 9;</code>
     * @return The idempotencyKey.
     */
    @java.lang.Override
    public java.lang.String getIdempotencyKey() {
      return instance.getIdempotencyKey();
    }
    /**
     * <code>string idempotency_key = 9;</code>
     * @return The bytes for idempotencyKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdempotencyKeyBytes() {
      return instance.getIdempotencyKeyBytes();
    }
    /**
     * <code>string idempotency_key = 9;</code>
     * @param value The idempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotencyKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setIdempotencyKey(value);
      return this;
    }
    /**
     * <code>string idempotency_key = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdempotencyKey() {
      copyOnWrite();
      instance.clearIdempotencyKey();
      return this;
    }
    /**
     * <code>string idempotency_key = 9;</code>
     * @param value The bytes for idempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotencyKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdempotencyKeyBytes(value);
      return this;
    }

    /**
     * <code>int64 issued_at_epoch_ms = 10;</code>
     * @return The issuedAtEpochMs.
     */
    @java.lang.Override
    public long getIssuedAtEpochMs() {
      return instance.getIssuedAtEpochMs();
    }
    /**
     * <code>int64 issued_at_epoch_ms = 10;</code>
     * @param value The issuedAtEpochMs to set.
     * @return This builder for chaining.
     */
    public Builder setIssuedAtEpochMs(long value) {
      copyOnWrite();
      instance.setIssuedAtEpochMs(value);
      return this;
    }
    /**
     * <code>int64 issued_at_epoch_ms = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearIssuedAtEpochMs() {
      copyOnWrite();
      instance.clearIssuedAtEpochMs();
      return this;
    }

    /**
     * <code>.leona.evidence.v1.ClientScopeDeclaration client_scope = 11;</code>
     */
    @java.lang.Override
    public boolean hasClientScope() {
      return instance.hasClientScope();
    }
    /**
     * <code>.leona.evidence.v1.ClientScopeDeclaration client_scope = 11;</code>
     */
    @java.lang.Override
    public io.leonasec.proto.v1.ClientScopeDeclaration getClientScope() {
      return instance.getClientScope();
    }
    /**
     * <code>.leona.evidence.v1.ClientScopeDeclaration client_scope = 11;</code>
     */
    public Builder setClientScope(io.leonasec.proto.v1.ClientScopeDeclaration value) {
      copyOnWrite();
      instance.setClientScope(value);
      return this;
      }
    /**
     * <code>.leona.evidence.v1.ClientScopeDeclaration client_scope = 11;</code>
     */
    public Builder setClientScope(
        io.leonasec.proto.v1.ClientScopeDeclaration.Builder builderForValue) {
      copyOnWrite();
      instance.setClientScope(builderForValue.build());
      return this;
    }
    /**
     * <code>.leona.evidence.v1.ClientScopeDeclaration client_scope = 11;</code>
     */
    public Builder mergeClientScope(io.leonasec.proto.v1.ClientScopeDeclaration value) {
      copyOnWrite();
      instance.mergeClientScope(value);
      return this;
    }
    /**
     * <code>.leona.evidence.v1.ClientScopeDeclaration client_scope = 11;</code>
     */
    public Builder clearClientScope() {  copyOnWrite();
      instance.clearClientScope();
      return this;
    }

    /**
     * <code>.leona.evidence.v1.EvidenceBatch evidence_batch = 12;</code>
     */
    @java.lang.Override
    public boolean hasEvidenceBatch() {
      return instance.hasEvidenceBatch();
    }
    /**
     * <code>.leona.evidence.v1.EvidenceBatch evidence_batch = 12;</code>
     */
    @java.lang.Override
    public io.leonasec.proto.v1.EvidenceBatch getEvidenceBatch() {
      return instance.getEvidenceBatch();
    }
    /**
     * <code>.leona.evidence.v1.EvidenceBatch evidence_batch = 12;</code>
     */
    public Builder setEvidenceBatch(io.leonasec.proto.v1.EvidenceBatch value) {
      copyOnWrite();
      instance.setEvidenceBatch(value);
      return this;
      }
    /**
     * <code>.leona.evidence.v1.EvidenceBatch evidence_batch = 12;</code>
     */
    public Builder setEvidenceBatch(
        io.leonasec.proto.v1.EvidenceBatch.Builder builderForValue) {
      copyOnWrite();
      instance.setEvidenceBatch(builderForValue.build());
      return this;
    }
    /**
     * <code>.leona.evidence.v1.EvidenceBatch evidence_batch = 12;</code>
     */
    public Builder mergeEvidenceBatch(io.leonasec.proto.v1.EvidenceBatch value) {
      copyOnWrite();
      instance.mergeEvidenceBatch(value);
      return this;
    }
    /**
     * <code>.leona.evidence.v1.EvidenceBatch evidence_batch = 12;</code>
     */
    public Builder clearEvidenceBatch() {  copyOnWrite();
      instance.clearEvidenceBatch();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:leona.evidence.v1.EvidenceIngestRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.leonasec.proto.v1.EvidenceIngestRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "protocolMajor_",
            "tenantId_",
            "appId_",
            "environmentId_",
            "installId_",
            "sessionId_",
            "requestId_",
            "nonce_",
            "idempotencyKey_",
            "issuedAtEpochMs_",
            "clientScope_",
            "evidenceBatch_",
          };
          java.lang.String info =
              "\u0000\f\u0000\u0001\u0001\f\f\u0000\u0000\u0000\u0001\u000b\u0002\u0208\u0003\u0208" +
              "\u0004\u0208\u0005\u0208\u0006\u0208\u0007\u0208\b\n\t\u0208\n\u0002\u000b\u1009" +
              "\u0000\f\u1009\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.leonasec.proto.v1.EvidenceIngestRequest> parser = PARSER;
        if (parser == null) {
          synchronized (io.leonasec.proto.v1.EvidenceIngestRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.leonasec.proto.v1.EvidenceIngestRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:leona.evidence.v1.EvidenceIngestRequest)
  private static final io.leonasec.proto.v1.EvidenceIngestRequest DEFAULT_INSTANCE;
  static {
    EvidenceIngestRequest defaultInstance = new EvidenceIngestRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      EvidenceIngestRequest.class, defaultInstance);
  }

  public static io.leonasec.proto.v1.EvidenceIngestRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<EvidenceIngestRequest> PARSER;

  public static com.google.protobuf.Parser<EvidenceIngestRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

