// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ingest.proto
// Protobuf Java Version: 4.29.4

package io.leonasec.proto.v1;

/**
 * Protobuf enum {@code leona.evidence.v1.EvidenceQuality}
 */
public enum EvidenceQuality
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>EVIDENCE_QUALITY_UNSPECIFIED = 0;</code>
   */
  EVIDENCE_QUALITY_UNSPECIFIED(0),
  /**
   * <code>EVIDENCE_QUALITY_RAW = 1;</code>
   */
  EVIDENCE_QUALITY_RAW(1),
  /**
   * <code>EVIDENCE_QUALITY_VERIFIED = 2;</code>
   */
  EVIDENCE_QUALITY_VERIFIED(2),
  /**
   * <code>EVIDENCE_QUALITY_REDACTED = 3;</code>
   */
  EVIDENCE_QUALITY_REDACTED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>EVIDENCE_QUALITY_UNSPECIFIED = 0;</code>
   */
  public static final int EVIDENCE_QUALITY_UNSPECIFIED_VALUE = 0;
  /**
   * <code>EVIDENCE_QUALITY_RAW = 1;</code>
   */
  public static final int EVIDENCE_QUALITY_RAW_VALUE = 1;
  /**
   * <code>EVIDENCE_QUALITY_VERIFIED = 2;</code>
   */
  public static final int EVIDENCE_QUALITY_VERIFIED_VALUE = 2;
  /**
   * <code>EVIDENCE_QUALITY_REDACTED = 3;</code>
   */
  public static final int EVIDENCE_QUALITY_REDACTED_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EvidenceQuality valueOf(int value) {
    return forNumber(value);
  }

  public static EvidenceQuality forNumber(int value) {
    switch (value) {
      case 0: return EVIDENCE_QUALITY_UNSPECIFIED;
      case 1: return EVIDENCE_QUALITY_RAW;
      case 2: return EVIDENCE_QUALITY_VERIFIED;
      case 3: return EVIDENCE_QUALITY_REDACTED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EvidenceQuality>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EvidenceQuality> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EvidenceQuality>() {
          @java.lang.Override
          public EvidenceQuality findValueByNumber(int number) {
            return EvidenceQuality.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return EvidenceQualityVerifier.INSTANCE;
  }

  private static final class EvidenceQualityVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new EvidenceQualityVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return EvidenceQuality.forNumber(number) != null;
          }
        };

  private final int value;

  private EvidenceQuality(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:leona.evidence.v1.EvidenceQuality)
}

