// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ingest.proto
// Protobuf Java Version: 4.29.4

package io.leonasec.proto.v1;

/**
 * Protobuf type {@code leona.evidence.v1.EvidenceEntry}
 */
public  final class EvidenceEntry extends
    com.google.protobuf.GeneratedMessageLite<
        EvidenceEntry, EvidenceEntry.Builder> implements
    // @@protoc_insertion_point(message_implements:leona.evidence.v1.EvidenceEntry)
    EvidenceEntryOrBuilder {
  private EvidenceEntry() {
    key_ = "";
  }
  private int valueCase_ = 0;
  private java.lang.Object value_;
  public enum ValueCase {
    BOOL_VALUE(5),
    INT_VALUE(6),
    UINT_VALUE(7),
    STRING_VALUE(8),
    BYTES_VALUE(9),
    ENUM_VALUE(10),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 5: return BOOL_VALUE;
        case 6: return INT_VALUE;
        case 7: return UINT_VALUE;
        case 8: return STRING_VALUE;
        case 9: return BYTES_VALUE;
        case 10: return ENUM_VALUE;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  private void clearValue() {
    valueCase_ = 0;
    value_ = null;
  }

  public static final int KEY_FIELD_NUMBER = 1;
  private java.lang.String key_;
  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    return key_;
  }
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(key_);
  }
  /**
   * <code>string key = 1;</code>
   * @param value The key to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setKey(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    key_ = value;
  }
  /**
   * <code>string key = 1;</code>
   */
  private void clearKey() {

    key_ = getDefaultInstance().getKey();
  }
  /**
   * <code>string key = 1;</code>
   * @param value The bytes for key to set.
   */
  private void setKeyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    key_ = value.toStringUtf8();

  }

  public static final int OBSERVED_AT_EPOCH_MS_FIELD_NUMBER = 2;
  private long observedAtEpochMs_;
  /**
   * <code>int64 observed_at_epoch_ms = 2;</code>
   * @return The observedAtEpochMs.
   */
  @java.lang.Override
  public long getObservedAtEpochMs() {
    return observedAtEpochMs_;
  }
  /**
   * <code>int64 observed_at_epoch_ms = 2;</code>
   * @param value The observedAtEpochMs to set.
   */
  private void setObservedAtEpochMs(long value) {
    
    observedAtEpochMs_ = value;
  }
  /**
   * <code>int64 observed_at_epoch_ms = 2;</code>
   */
  private void clearObservedAtEpochMs() {

    observedAtEpochMs_ = 0L;
  }

  public static final int SOURCE_FIELD_NUMBER = 3;
  private int source_;
  /**
   * <code>.leona.evidence.v1.EvidenceSource source = 3;</code>
   * @return The enum numeric value on the wire for source.
   */
  @java.lang.Override
  public int getSourceValue() {
    return source_;
  }
  /**
   * <code>.leona.evidence.v1.EvidenceSource source = 3;</code>
   * @return The source.
   */
  @java.lang.Override
  public io.leonasec.proto.v1.EvidenceSource getSource() {
    io.leonasec.proto.v1.EvidenceSource result = io.leonasec.proto.v1.EvidenceSource.forNumber(source_);
    return result == null ? io.leonasec.proto.v1.EvidenceSource.UNRECOGNIZED : result;
  }
  /**
   * <code>.leona.evidence.v1.EvidenceSource source = 3;</code>
   * @param value The enum numeric value on the wire for source to set.
   */
  private void setSourceValue(int value) {
      source_ = value;
  }
  /**
   * <code>.leona.evidence.v1.EvidenceSource source = 3;</code>
   * @param value The source to set.
   */
  private void setSource(io.leonasec.proto.v1.EvidenceSource value) {
    source_ = value.getNumber();

  }
  /**
   * <code>.leona.evidence.v1.EvidenceSource source = 3;</code>
   */
  private void clearSource() {

    source_ = 0;
  }

  public static final int QUALITY_FIELD_NUMBER = 4;
  private int quality_;
  /**
   * <code>.leona.evidence.v1.EvidenceQuality quality = 4;</code>
   * @return The enum numeric value on the wire for quality.
   */
  @java.lang.Override
  public int getQualityValue() {
    return quality_;
  }
  /**
   * <code>.leona.evidence.v1.EvidenceQuality quality = 4;</code>
   * @return The quality.
   */
  @java.lang.Override
  public io.leonasec.proto.v1.EvidenceQuality getQuality() {
    io.leonasec.proto.v1.EvidenceQuality result = io.leonasec.proto.v1.EvidenceQuality.forNumber(quality_);
    return result == null ? io.leonasec.proto.v1.EvidenceQuality.UNRECOGNIZED : result;
  }
  /**
   * <code>.leona.evidence.v1.EvidenceQuality quality = 4;</code>
   * @param value The enum numeric value on the wire for quality to set.
   */
  private void setQualityValue(int value) {
      quality_ = value;
  }
  /**
   * <code>.leona.evidence.v1.EvidenceQuality quality = 4;</code>
   * @param value The quality to set.
   */
  private void setQuality(io.leonasec.proto.v1.EvidenceQuality value) {
    quality_ = value.getNumber();

  }
  /**
   * <code>.leona.evidence.v1.EvidenceQuality quality = 4;</code>
   */
  private void clearQuality() {

    quality_ = 0;
  }

  public static final int BOOL_VALUE_FIELD_NUMBER = 5;
  /**
   * <code>bool bool_value = 5;</code>
   * @return Whether the boolValue field is set.
   */
  @java.lang.Override
  public boolean hasBoolValue() {
    return valueCase_ == 5;
  }
  /**
   * <code>bool bool_value = 5;</code>
   * @return The boolValue.
   */
  @java.lang.Override
  public boolean getBoolValue() {
    if (valueCase_ == 5) {
      return (java.lang.Boolean) value_;
    }
    return false;
  }
  /**
   * <code>bool bool_value = 5;</code>
   * @param value The boolValue to set.
   */
  private void setBoolValue(boolean value) {
    valueCase_ = 5;
    value_ = value;
  }
  /**
   * <code>bool bool_value = 5;</code>
   */
  private void clearBoolValue() {
    if (valueCase_ == 5) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int INT_VALUE_FIELD_NUMBER = 6;
  /**
   * <code>sint64 int_value = 6;</code>
   * @return Whether the intValue field is set.
   */
  @java.lang.Override
  public boolean hasIntValue() {
    return valueCase_ == 6;
  }
  /**
   * <code>sint64 int_value = 6;</code>
   * @return The intValue.
   */
  @java.lang.Override
  public long getIntValue() {
    if (valueCase_ == 6) {
      return (java.lang.Long) value_;
    }
    return 0L;
  }
  /**
   * <code>sint64 int_value = 6;</code>
   * @param value The intValue to set.
   */
  private void setIntValue(long value) {
    valueCase_ = 6;
    value_ = value;
  }
  /**
   * <code>sint64 int_value = 6;</code>
   */
  private void clearIntValue() {
    if (valueCase_ == 6) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int UINT_VALUE_FIELD_NUMBER = 7;
  /**
   * <code>fixed64 uint_value = 7;</code>
   * @return Whether the uintValue field is set.
   */
  @java.lang.Override
  public boolean hasUintValue() {
    return valueCase_ == 7;
  }
  /**
   * <code>fixed64 uint_value = 7;</code>
   * @return The uintValue.
   */
  @java.lang.Override
  public long getUintValue() {
    if (valueCase_ == 7) {
      return (java.lang.Long) value_;
    }
    return 0L;
  }
  /**
   * <code>fixed64 uint_value = 7;</code>
   * @param value The uintValue to set.
   */
  private void setUintValue(long value) {
    valueCase_ = 7;
    value_ = value;
  }
  /**
   * <code>fixed64 uint_value = 7;</code>
   */
  private void clearUintValue() {
    if (valueCase_ == 7) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int STRING_VALUE_FIELD_NUMBER = 8;
  /**
   * <code>string string_value = 8;</code>
   * @return Whether the stringValue field is set.
   */
  @java.lang.Override
  public boolean hasStringValue() {
    return valueCase_ == 8;
  }
  /**
   * <code>string string_value = 8;</code>
   * @return The stringValue.
   */
  @java.lang.Override
  public java.lang.String getStringValue() {
    java.lang.String ref = "";
    if (valueCase_ == 8) {
      ref = (java.lang.String) value_;
    }
    return ref;
  }
  /**
   * <code>string string_value = 8;</code>
   * @return The bytes for stringValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStringValueBytes() {
    java.lang.String ref = "";
    if (valueCase_ == 8) {
      ref = (java.lang.String) value_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <code>string string_value = 8;</code>
   * @param value The stringValue to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setStringValue(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    valueCase_ = 8;
    value_ = value;
  }
  /**
   * <code>string string_value = 8;</code>
   */
  private void clearStringValue() {
    if (valueCase_ == 8) {
      valueCase_ = 0;
      value_ = null;
    }
  }
  /**
   * <code>string string_value = 8;</code>
   * @param value The bytes for stringValue to set.
   */
  private void setStringValueBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    value_ = value.toStringUtf8();
    valueCase_ = 8;
  }

  public static final int BYTES_VALUE_FIELD_NUMBER = 9;
  /**
   * <code>bytes bytes_value = 9;</code>
   * @return Whether the bytesValue field is set.
   */
  @java.lang.Override
  public boolean hasBytesValue() {
    return valueCase_ == 9;
  }
  /**
   * <code>bytes bytes_value = 9;</code>
   * @return The bytesValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBytesValue() {
    if (valueCase_ == 9) {
      return (com.google.protobuf.ByteString) value_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }
  /**
   * <code>bytes bytes_value = 9;</code>
   * @param value The bytesValue to set.
   */
  private void setBytesValue(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  valueCase_ = 9;
    value_ = value;
  }
  /**
   * <code>bytes bytes_value = 9;</code>
   */
  private void clearBytesValue() {
    if (valueCase_ == 9) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int ENUM_VALUE_FIELD_NUMBER = 10;
  /**
   * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
   * @return Whether the enumValue field is set.
   */
  @java.lang.Override
  public boolean hasEnumValue() {
    return valueCase_ == 10;
  }
  /**
   * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
   * @return The enum numeric value on the wire for enumValue.
   */
  @java.lang.Override
  public int getEnumValueValue() {
    if (valueCase_ == 10) {
      return (java.lang.Integer) value_;
    }
    return 0;
  }
  /**
   * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
   * @return The enumValue.
   */
  @java.lang.Override
  public io.leonasec.proto.v1.EvidenceEnum getEnumValue() {
    if (valueCase_ == 10) {
      io.leonasec.proto.v1.EvidenceEnum result = io.leonasec.proto.v1.EvidenceEnum.forNumber((java.lang.Integer) value_);
      return result == null ? io.leonasec.proto.v1.EvidenceEnum.UNRECOGNIZED : result;
    }
    return io.leonasec.proto.v1.EvidenceEnum.EVIDENCE_ENUM_UNSPECIFIED;
  }
  /**
   * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
   * @param value The enum numeric value on the wire for enumValue to set.
   */
  private void setEnumValueValue(int value) {
    valueCase_ = 10;
    value_ = value;
  }
  /**
   * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
   * @param value The enumValue to set.
   */
  private void setEnumValue(io.leonasec.proto.v1.EvidenceEnum value) {
    value_ = value.getNumber();
    valueCase_ = 10;
  }
  /**
   * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
   */
  private void clearEnumValue() {
    if (valueCase_ == 10) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static io.leonasec.proto.v1.EvidenceEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.leonasec.proto.v1.EvidenceEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.leonasec.proto.v1.EvidenceEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.leonasec.proto.v1.EvidenceEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.leonasec.proto.v1.EvidenceEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.leonasec.proto.v1.EvidenceEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.leonasec.proto.v1.EvidenceEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.leonasec.proto.v1.EvidenceEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static io.leonasec.proto.v1.EvidenceEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static io.leonasec.proto.v1.EvidenceEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.leonasec.proto.v1.EvidenceEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.leonasec.proto.v1.EvidenceEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.leonasec.proto.v1.EvidenceEntry prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code leona.evidence.v1.EvidenceEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.leonasec.proto.v1.EvidenceEntry, Builder> implements
      // @@protoc_insertion_point(builder_implements:leona.evidence.v1.EvidenceEntry)
      io.leonasec.proto.v1.EvidenceEntryOrBuilder {
    // Construct using io.leonasec.proto.v1.EvidenceEntry.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public ValueCase
        getValueCase() {
      return instance.getValueCase();
    }

    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }


    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      return instance.getKey();
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      return instance.getKeyBytes();
    }
    /**
     * <code>string key = 1;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setKey(value);
      return this;
    }
    /**
     * <code>string key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      copyOnWrite();
      instance.clearKey();
      return this;
    }
    /**
     * <code>string key = 1;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKeyBytes(value);
      return this;
    }

    /**
     * <code>int64 observed_at_epoch_ms = 2;</code>
     * @return The observedAtEpochMs.
     */
    @java.lang.Override
    public long getObservedAtEpochMs() {
      return instance.getObservedAtEpochMs();
    }
    /**
     * <code>int64 observed_at_epoch_ms = 2;</code>
     * @param value The observedAtEpochMs to set.
     * @return This builder for chaining.
     */
    public Builder setObservedAtEpochMs(long value) {
      copyOnWrite();
      instance.setObservedAtEpochMs(value);
      return this;
    }
    /**
     * <code>int64 observed_at_epoch_ms = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearObservedAtEpochMs() {
      copyOnWrite();
      instance.clearObservedAtEpochMs();
      return this;
    }

    /**
     * <code>.leona.evidence.v1.EvidenceSource source = 3;</code>
     * @return The enum numeric value on the wire for source.
     */
    @java.lang.Override
    public int getSourceValue() {
      return instance.getSourceValue();
    }
    /**
     * <code>.leona.evidence.v1.EvidenceSource source = 3;</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSourceValue(int value) {
      copyOnWrite();
      instance.setSourceValue(value);
      return this;
    }
    /**
     * <code>.leona.evidence.v1.EvidenceSource source = 3;</code>
     * @return The source.
     */
    @java.lang.Override
    public io.leonasec.proto.v1.EvidenceSource getSource() {
      return instance.getSource();
    }
    /**
     * <code>.leona.evidence.v1.EvidenceSource source = 3;</code>
     * @param value The enum numeric value on the wire for source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(io.leonasec.proto.v1.EvidenceSource value) {
      copyOnWrite();
      instance.setSource(value);
      return this;
    }
    /**
     * <code>.leona.evidence.v1.EvidenceSource source = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      copyOnWrite();
      instance.clearSource();
      return this;
    }

    /**
     * <code>.leona.evidence.v1.EvidenceQuality quality = 4;</code>
     * @return The enum numeric value on the wire for quality.
     */
    @java.lang.Override
    public int getQualityValue() {
      return instance.getQualityValue();
    }
    /**
     * <code>.leona.evidence.v1.EvidenceQuality quality = 4;</code>
     * @param value The quality to set.
     * @return This builder for chaining.
     */
    public Builder setQualityValue(int value) {
      copyOnWrite();
      instance.setQualityValue(value);
      return this;
    }
    /**
     * <code>.leona.evidence.v1.EvidenceQuality quality = 4;</code>
     * @return The quality.
     */
    @java.lang.Override
    public io.leonasec.proto.v1.EvidenceQuality getQuality() {
      return instance.getQuality();
    }
    /**
     * <code>.leona.evidence.v1.EvidenceQuality quality = 4;</code>
     * @param value The enum numeric value on the wire for quality to set.
     * @return This builder for chaining.
     */
    public Builder setQuality(io.leonasec.proto.v1.EvidenceQuality value) {
      copyOnWrite();
      instance.setQuality(value);
      return this;
    }
    /**
     * <code>.leona.evidence.v1.EvidenceQuality quality = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuality() {
      copyOnWrite();
      instance.clearQuality();
      return this;
    }

    /**
     * <code>bool bool_value = 5;</code>
     * @return Whether the boolValue field is set.
     */
    @java.lang.Override
    public boolean hasBoolValue() {
      return instance.hasBoolValue();
    }
    /**
     * <code>bool bool_value = 5;</code>
     * @return The boolValue.
     */
    @java.lang.Override
    public boolean getBoolValue() {
      return instance.getBoolValue();
    }
    /**
     * <code>bool bool_value = 5;</code>
     * @param value The boolValue to set.
     * @return This builder for chaining.
     */
    public Builder setBoolValue(boolean value) {
      copyOnWrite();
      instance.setBoolValue(value);
      return this;
    }
    /**
     * <code>bool bool_value = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolValue() {
      copyOnWrite();
      instance.clearBoolValue();
      return this;
    }

    /**
     * <code>sint64 int_value = 6;</code>
     * @return Whether the intValue field is set.
     */
    @java.lang.Override
    public boolean hasIntValue() {
      return instance.hasIntValue();
    }
    /**
     * <code>sint64 int_value = 6;</code>
     * @return The intValue.
     */
    @java.lang.Override
    public long getIntValue() {
      return instance.getIntValue();
    }
    /**
     * <code>sint64 int_value = 6;</code>
     * @param value The intValue to set.
     * @return This builder for chaining.
     */
    public Builder setIntValue(long value) {
      copyOnWrite();
      instance.setIntValue(value);
      return this;
    }
    /**
     * <code>sint64 int_value = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntValue() {
      copyOnWrite();
      instance.clearIntValue();
      return this;
    }

    /**
     * <code>fixed64 uint_value = 7;</code>
     * @return Whether the uintValue field is set.
     */
    @java.lang.Override
    public boolean hasUintValue() {
      return instance.hasUintValue();
    }
    /**
     * <code>fixed64 uint_value = 7;</code>
     * @return The uintValue.
     */
    @java.lang.Override
    public long getUintValue() {
      return instance.getUintValue();
    }
    /**
     * <code>fixed64 uint_value = 7;</code>
     * @param value The uintValue to set.
     * @return This builder for chaining.
     */
    public Builder setUintValue(long value) {
      copyOnWrite();
      instance.setUintValue(value);
      return this;
    }
    /**
     * <code>fixed64 uint_value = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUintValue() {
      copyOnWrite();
      instance.clearUintValue();
      return this;
    }

    /**
     * <code>string string_value = 8;</code>
     * @return Whether the stringValue field is set.
     */
    @java.lang.Override
    public boolean hasStringValue() {
      return instance.hasStringValue();
    }
    /**
     * <code>string string_value = 8;</code>
     * @return The stringValue.
     */
    @java.lang.Override
    public java.lang.String getStringValue() {
      return instance.getStringValue();
    }
    /**
     * <code>string string_value = 8;</code>
     * @return The bytes for stringValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      return instance.getStringValueBytes();
    }
    /**
     * <code>string string_value = 8;</code>
     * @param value The stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValue(
        java.lang.String value) {
      copyOnWrite();
      instance.setStringValue(value);
      return this;
    }
    /**
     * <code>string string_value = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringValue() {
      copyOnWrite();
      instance.clearStringValue();
      return this;
    }
    /**
     * <code>string string_value = 8;</code>
     * @param value The bytes for stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValueBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStringValueBytes(value);
      return this;
    }

    /**
     * <code>bytes bytes_value = 9;</code>
     * @return Whether the bytesValue field is set.
     */
    @java.lang.Override
    public boolean hasBytesValue() {
      return instance.hasBytesValue();
    }
    /**
     * <code>bytes bytes_value = 9;</code>
     * @return The bytesValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytesValue() {
      return instance.getBytesValue();
    }
    /**
     * <code>bytes bytes_value = 9;</code>
     * @param value The bytesValue to set.
     * @return This builder for chaining.
     */
    public Builder setBytesValue(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBytesValue(value);
      return this;
    }
    /**
     * <code>bytes bytes_value = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearBytesValue() {
      copyOnWrite();
      instance.clearBytesValue();
      return this;
    }

    /**
     * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
     * @return Whether the enumValue field is set.
     */
    @java.lang.Override
    public boolean hasEnumValue() {
      return instance.hasEnumValue();
    }
    /**
     * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
     * @return The enum numeric value on the wire for enumValue.
     */
    @java.lang.Override
    public int getEnumValueValue() {
      return instance.getEnumValueValue();
    }
    /**
     * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
     * @param value The enum numeric value on the wire for enumValue to set.
     * @return This builder for chaining.
     */
    public Builder setEnumValueValue(int value) {
      copyOnWrite();
      instance.setEnumValueValue(value);
      return this;
    }
    /**
     * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
     * @return The enumValue.
     */
    @java.lang.Override
    public io.leonasec.proto.v1.EvidenceEnum getEnumValue() {
      return instance.getEnumValue();
    }
    /**
     * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
     * @param value The enumValue to set.
     * @return This builder for chaining.
     */
    public Builder setEnumValue(io.leonasec.proto.v1.EvidenceEnum value) {
      copyOnWrite();
      instance.setEnumValue(value);
      return this;
    }
    /**
     * <code>.leona.evidence.v1.EvidenceEnum enum_value = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnumValue() {
      copyOnWrite();
      instance.clearEnumValue();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:leona.evidence.v1.EvidenceEntry)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.leonasec.proto.v1.EvidenceEntry();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "value_",
            "valueCase_",
            "key_",
            "observedAtEpochMs_",
            "source_",
            "quality_",
          };
          java.lang.String info =
              "\u0000\n\u0001\u0000\u0001\n\n\u0000\u0000\u0000\u0001\u0208\u0002\u0002\u0003\f" +
              "\u0004\f\u0005:\u0000\u0006C\u0000\u00078\u0000\b\u023b\u0000\t=\u0000\n?\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.leonasec.proto.v1.EvidenceEntry> parser = PARSER;
        if (parser == null) {
          synchronized (io.leonasec.proto.v1.EvidenceEntry.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.leonasec.proto.v1.EvidenceEntry>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:leona.evidence.v1.EvidenceEntry)
  private static final io.leonasec.proto.v1.EvidenceEntry DEFAULT_INSTANCE;
  static {
    EvidenceEntry defaultInstance = new EvidenceEntry();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      EvidenceEntry.class, defaultInstance);
  }

  public static io.leonasec.proto.v1.EvidenceEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<EvidenceEntry> PARSER;

  public static com.google.protobuf.Parser<EvidenceEntry> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

