global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: leona-local

rule_files:
  - /etc/prometheus/prometheus-alerts.yml

scrape_configs:
  - job_name: gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["gateway:8080"]

  - job_name: ingestion-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ingestion-service:8081"]

  - job_name: query-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["query-service:8082"]

  - job_name: admin-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["admin-service:8083"]

  - job_name: worker-event-persister
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["worker-event-persister:8084"]
