/*
 * Copyright 2026 Leona Contributors.
 * Licensed under the Apache License, Version 2.0.
 */
package io.leonasec.leona.internal.identity

/**
 * Privacy registration for every identity/evidence field emitted by the
 * Android collector. The registry is metadata only; it does not grant an
 * application permission or make a risk decision.
 */
internal data class IdentityFieldRegistration(
    val name: String,
    val source: String,
    val apiRange: String,
    val permission: String,
    val purpose: String,
    val stability: String,
    val distinctiveness: String,
    val spoofability: String,
    val privacyLevel: String,
    val defaultEnabled: Boolean,
    val protection: String,
    val retention: String,
    val missingStrategy: String,
)

internal object IdentityFieldRegistryV1 {
    const val VERSION = "v1"
    const val API_RANGE = "23-36"

    /** Stable ordering keeps documentation, audits, and tests reproducible. */
    val fields: List<IdentityFieldRegistration> = listOf(
        field(
            name = "install_id",
            source = "Android Keystore-backed random UUID",
            purpose = "Correlate one app installation for server evidence joins",
            stability = "stable across process death, reboot, and upgrade; rotates on clear-data or reinstall",
            distinctiveness = "high within the tenant after server issuance",
            spoofability = "client claim; low trust until server binding",
            privacyLevel = "pseudonymous",
            protection = "AES-GCM at rest; SHA-256 in protected request metadata; FULL_DEBUG may expose caller-local raw diagnostics",
            retention = "until app data is cleared, uninstall, or server expiry",
            missingStrategy = "emit ephemeral in-memory value with KEYSTORE_UNAVAILABLE evidence; never use plaintext fallback",
        ),
        field(
            name = "session_id",
            source = "cryptographically random process initialization",
            purpose = "Correlate one SDK process session and prevent install/session conflation",
            stability = "changes for every process initialization",
            distinctiveness = "high per process",
            spoofability = "client claim; low trust",
            privacyLevel = "pseudonymous",
            protection = "memory only; SHA-256 in SDK-controlled request metadata",
            retention = "process lifetime only",
            missingStrategy = "fail closed for callers that require a session; no persisted fallback",
        ),
        field(
            name = "canonical_device_id",
            source = "server-issued response only",
            purpose = "Carry a server-owned device correlation handle",
            stability = "server policy controlled",
            distinctiveness = "server-defined",
            spoofability = "client claim until authenticated server response",
            privacyLevel = "pseudonymous",
            protection = "AES-GCM at rest; SHA-256 in client request metadata",
            retention = "server/client policy; cleared with install lifecycle reset",
            missingStrategy = "null; use temporary local evidence correlation only",
        ),
        field(
            name = "fingerprint_hash",
            source = "canonicalized local profile and app-scoped anchors",
            purpose = "Provide a low-trust, reproducible evidence correlation hint",
            stability = "stable-ish; may change with OS/app/device profile",
            distinctiveness = "medium and non-authoritative",
            spoofability = "high; client-derived",
            privacyLevel = "pseudonymous",
            protection = "SHA-256; no raw seed leaves the SDK",
            retention = "cached only while the snapshot is valid",
            missingStrategy = "omit from request if unavailable",
        ),
        field(
            name = "android_id",
            source = "Settings.Secure.ANDROID_ID (app/user scoped)",
            purpose = "Optional local anchor for distinguishing app instances",
            stability = "OS/user/signing-key scoped; not guaranteed across reset",
            distinctiveness = "medium",
            spoofability = "medium to high",
            privacyLevel = "sensitive pseudonymous",
            protection = "not sent raw in secure network payload; retained in AES-GCM snapshot; FULL_DEBUG may expose caller-local raw diagnostics",
            retention = "not persisted separately",
            missingStrategy = "omit when unavailable, placeholder, or disabled by policy",
        ),
        field(
            name = "package_name",
            source = "ApplicationContext.packageName",
            purpose = "Attribute evidence to the embedding application",
            stability = "stable for an installed package",
            distinctiveness = "high for application attribution",
            spoofability = "medium; verified against server policy where configured",
            privacyLevel = "ordinary application metadata",
            protection = "inside caller-owned protected request context",
            retention = "request/evidence retention policy",
            missingStrategy = "fail closed before collection if context has no package",
        ),
        field(
            name = "app_version",
            source = "PackageManager package metadata",
            purpose = "Version and rollout correlation",
            stability = "stable until upgrade",
            distinctiveness = "low",
            spoofability = "medium",
            privacyLevel = "ordinary application metadata",
            protection = "inside protected request context",
            retention = "request/evidence retention policy",
            missingStrategy = "use null/0 and mark unavailable",
        ),
        field(
            name = "installer_package",
            source = "PackageManager install source",
            purpose = "Distribution-channel evidence",
            stability = "stable until package distribution changes",
            distinctiveness = "medium",
            spoofability = "medium",
            privacyLevel = "ordinary application metadata",
            protection = "inside protected request context; never an authorization scope",
            retention = "request/evidence retention policy",
            missingStrategy = "null when API/provider does not expose it",
        ),
        field(
            name = "signing_cert_sha256",
            source = "PackageManager signing certificate digest",
            purpose = "Application integrity evidence",
            stability = "stable until signer rotation",
            distinctiveness = "high for an app signer",
            spoofability = "medium; server baseline required",
            privacyLevel = "ordinary application integrity metadata",
            protection = "SHA-256 digest inside protected request context",
            retention = "request/evidence retention policy",
            missingStrategy = "empty list and mark unavailable",
        ),
        field(
            name = "device_profile",
            source = "Build brand/model/manufacturer/device/product/hardware",
            purpose = "Environment evidence and coarse correlation",
            stability = "stable-ish; can vary by image or vendor",
            distinctiveness = "low to medium",
            spoofability = "high; device properties are client-readable",
            privacyLevel = "ordinary device metadata",
            protection = "raw profile remains in protected evidence payload; hash seeds stay local",
            retention = "request/evidence retention policy",
            missingStrategy = "empty strings/arrays; continue evidence collection",
        ),
        field(
            name = "sdk_int",
            source = "Build.VERSION.SDK_INT",
            purpose = "Interpret API-specific evidence and compatibility",
            stability = "stable for an OS image",
            distinctiveness = "low",
            spoofability = "medium",
            privacyLevel = "ordinary device metadata",
            protection = "inside protected request context",
            retention = "request/evidence retention policy",
            missingStrategy = "0/unknown",
        ),
        field(
            name = "abis",
            source = "Build.SUPPORTED_ABIS",
            purpose = "Native ABI compatibility evidence",
            stability = "stable for an installed image",
            distinctiveness = "low",
            spoofability = "medium",
            privacyLevel = "ordinary device metadata",
            protection = "inside protected request context",
            retention = "request/evidence retention policy",
            missingStrategy = "empty list",
        ),
        field(
            name = "locale_timezone_screen",
            source = "Locale, TimeZone, and display metrics",
            purpose = "Contextual evidence and support diagnostics",
            stability = "changes with user settings/configuration",
            distinctiveness = "low",
            spoofability = "high",
            privacyLevel = "low sensitivity contextual metadata",
            protection = "inside protected request context; screen is summary only",
            retention = "request/evidence retention policy",
            missingStrategy = "null or empty; continue",
        ),
        field(
            name = "risk_signals",
            source = "local Java/native detector observations",
            permission = "ACCESS_NETWORK_STATE (normal, optional); Settings provider (no dangerous permission)",
            purpose = "Report neutral evidence observations to the backend",
            stability = "volatile and policy dependent",
            distinctiveness = "not an identity",
            spoofability = "high; client evidence",
            privacyLevel = "security telemetry",
            protection = "protected request context; deprecated aliases remain low trust",
            retention = "server evidence retention policy",
            missingStrategy = "empty set; never infer a verdict",
        ),
        field(
            name = "tenant_app_environment",
            source = "caller configuration",
            purpose = "Route a request to the intended backend context",
            stability = "stable for one configured client",
            distinctiveness = "high for routing",
            spoofability = "client supplied; never an authorization scope authority",
            privacyLevel = "application configuration",
            protection = "only in the protected request context",
            retention = "request/evidence retention policy",
            missingStrategy = "tenant nullable; app default; environment nullable",
        ),
    )

    private fun field(
        name: String,
        source: String,
        purpose: String,
        stability: String,
        distinctiveness: String,
        spoofability: String,
        privacyLevel: String,
        protection: String,
        retention: String,
        missingStrategy: String,
        permission: String = "none",
        defaultEnabled: Boolean = true,
    ): IdentityFieldRegistration = IdentityFieldRegistration(
        name = name,
        source = source,
        apiRange = API_RANGE,
        permission = permission,
        purpose = purpose,
        stability = stability,
        distinctiveness = distinctiveness,
        spoofability = spoofability,
        privacyLevel = privacyLevel,
        defaultEnabled = defaultEnabled,
        protection = protection,
        retention = retention,
        missingStrategy = missingStrategy,
    )
}
